### PR TITLE
NULL replacement

### PR DESCRIPTION
**Pull request by Quaker762**

### CODE REVIEW

**Comment by Quaker762** [comment]
My god, Find and replace REALLY screwed up oops

**Comment by wornwinter** [comment]
Haha oh no. Btw, this might help: https://github.com/wornwinter/DMGe/wiki/Tetris-Disassembly-(Partial)

First bit of code for tetris. More to come :)

**Comment by Quaker762** [comment]
Ah, okay sweet, that's going to be a major help. Should probably write a disassembler eventually, shouldn't be too complex lol

**Comment by Quaker762** [comment]
Oh Crap, merge conflict

**Pull request closed without merging**
