### PR TITLE
Added correct MMU functinos to CPU

### PR DESCRIPTION
**Pull request by Quaker762**
Starting to get back into things with programming (been off for the past week :( ).  Basically just replaced any comments I had for the MMU in the CPU file with actual functions.

Also, I've been having issues with the emulator. When I load it up, I get no debug input line and no output, even though I have tetris.gb in the roms folder.

### CODE REVIEW

**Comment by wornwinter** [comment]
I'll have a look into it, but I'm going to suggest something a little controversial lol.

I'm thinking we should leave the debugger until we have the emulator running correctly, because it just seems to be complicating things at the minute.

**Comment by wornwinter** [comment]
One other thing too. I noticed that you're setting search directories in the project to find Boost etc. What I'd recommend is if you install the boost libraries and headers into your MinGW default search directories, as I have to go in and change it each time before I commit, and I'm sure you have to do the same.

I've also modified the project file to search the include directory of the project without specifying the whole path.

**Comment by wornwinter** [comment]
Added a few more opcodes and enabled debug text output too. Just make sure you have roms/bios.bin and roms/tetris.gb. I think we should work on getting the BIOS to run completely before we progress any further.

**Comment by wornwinter** [comment]
Just one final note as well. If you run the current master branch, it'll actually run the first part of the BIOS code - Zeroing 0x8000 to 0x9FFF in memory. Problem is, it's extremely slow, but this is down to calling so much debug output. Just undefine "_DEBUG" to disable it, and it's done in less than a second.

**Comment by Quaker762** [comment]
Okay all good, the debugger can wait to be honest. It'd much better for us to have a running CPU first. Worked out why I wasn't getting debug output, I forgot you could #define symbols in compiler so I got that going. 

As for adding dependency paths, I just add the files recursively every time I pull from master, it's not really a big deal. I just keep forgetting not to commit MY .depend file (added it to my .gitignore, ironically git is ignoring the fact I've told it to ignore it lmao).

We should definitely implement the BIOS before anything else. Isn't the gameboy BIOS in the first couple of bytes of every cartridge??

**Comment by wornwinter** [comment]
Yeah, sorry. I should have mentioned the defines lol.

I wouldn't worry too much about the .depend. It's a minor issue tbh.

And it's not located on the cartridge. It's a 256 byte on-chip ROM. You can download it for free online. Basically when the gameboy turns on, it's mapped to 0x000 to 0x100. It unmaps itself when it's finished running and jumps to 0x100, and maps where it was to the same location on the cartridge. In theory that should already be implemented within the MMU, so we don't need to worry about that.

The task now is just to keep running the bios, and every time we get an unrecognised opcode, we need to implement the opcode. As long as you have roms/tetris.gb and roms/bios.bin you should be able to start on that, as it is already emulating the bios. Just needs some more opcodes implemented. If you want to work on that, I've already made a start, so you should be able to take over from there, and I'll work on a barebones GPU and some SDL boiler plate code.

All the bios opcodes will need to be implemented before the GPU can really move forward though. From memory, I had to implement ~60 opcodes in total for the bios to run. You okay to do that? Or would you rather I work on the CPU and you can work elsewhere? I don't mind either way.

**Comment by Quaker762** [comment]
Nah it's okay I've got it with the CPU. I've got the BIOS file up and running, and I'm implementing opcodes at the moment. I'm going to try and get the entire BIOS running, so I'm good for the CPU at the moment.

**Comment by wornwinter** [comment]
Okay that's cool. Have fun lol. I know it's a bit soul destroying, but there's nothing like writing some code and watching something run (or not) like it's supposed to.

Let me know if you need any help at all.

**Comment by wornwinter** [comment]
Oh and of course, I can link you. Sorry just didn't read properly lol.

I've been doing some posts about the development about DMGe, I've linked all my resources in at the bottom:

https://wornwinter.wordpress.com/2015/02/14/adventures-in-gameboy-emulation-part-2-the-cpu/

Hope that helps.

**Pull request merged**
