### PR TITLE
Input stuff

### PR DESCRIPTION
**Pull request by Quaker762**
Joypad IRQ, actual joypad stuff and the canvas now accepts keyboard
input. Currently just prints out the keycode.

### CODE REVIEW

**Comment by Quaker762** [comment]
By the way, I could see some issues with having the key checking functions in the canvas instead of the frame (mainly where the input object is actually created with *new*), but we should be fine.

**Comment by wornwinter** [comment]
Great work. Sorry for being so quiet recently, been pretty busy. I'll see if I can move that code out of the canvas, but it's not the end of the world. I mean the canvas to basically be the "door" between the user and the emulated gameboy, so to speak lol.

**Comment by Quaker762** [comment]
Nah all good mate no problems. Yeah I get what you mean, unfortunately wx doesn't like to have key listeners attached to the actual frame lol (or at least that's what I got from the document).

**Comment by wornwinter** [comment]
I haven't looked into it at all, so looks good to me :P. Haven't been on much because I'm out of the house a lot and my laptop's bit the dust :(

**Comment by Quaker762** [comment]
No worries mate. I'm pretty busy myself so I've got no time either, also the laptop dying is a bit of a downer lmao.

**Pull request merged**
