### PR TITLE
Input Class stub

### PR DESCRIPTION
**Pull request by Quaker762**
Created a class for input and left a comment regarding implementation.
Much more research required :D

### CODE REVIEW

**Comment by Quaker762** [comment]
Just a quick note, I have no idea what to do with the GPU, so I'm probably going to do some other stuff lol :P

**Comment by wornwinter** [comment]
Looks good. As for IRQ's, that basic functionality is implemented already in the CPU. And yeah, just work on getting stuff like controls and sound working. I need to get the GPU fixed. Still can't work out what's wrong with it.

**Comment by Quaker762** [comment]
Yeah I'm not sure either. For me it flashes between a screen full of 0s and the copyright info. It's also odd how it hangs doing that. It's probably an opcode doing something it shouldn't.

**Comment by wornwinter** [comment]
I had thought it was maybe an opcode screwing up (I'd guess a jump somewhere), but it's going to take quite a while to find out where it's going wrong lol

**Pull request merged**
