### PR TITLE
More opcodes

### PR DESCRIPTION
**Pull request by Quaker762**
More opcodes implemented. Program counter reaches 0x100 (game program)
before hitting a NOP :)

### CODE REVIEW

**Comment by wornwinter** [comment]
You sir are a legend. This has made my day so much easier lol. I can just do graphics now :D

**Comment by Quaker762** [comment]
Mind if I work on Graphics with you? Wouldn't mind learning a bit more about it, it's my weakest point lol.

**Comment by wornwinter** [comment]
Not at all, the more help the better. I'll get backgrounds sorted, cause we're 99% there on that front, but if you want to look into sprites and OAM go for it. I have no clue about either of them, and I just spent 2 days wrecking my head trying to understand the tile system lol.

**Comment by wornwinter** [comment]
Also things like the rest of the graphics registers and the graphics modes need to be done.

**Comment by Quaker762** [comment]
Ahaha yeah the tile system is an absolute bitch. I'll get looking into some things. I have an idea for a few of the registers, especially the palette (Register FF47 I think), just need to work out the implementation lol.

**Comment by wornwinter** [comment]
If you had a look at the palette that'd be great. I'm already storing the colour values into tileset[][][].

Basically any pixel in tileset[][][] will be 0, 1, 2 or 3. Each one of those corresponds to a colour in the palette.

**Comment by wornwinter** [comment]
At the minute, I know the BIOS only draws black or white, so I'm doing a dirty hack that's basically "if the pixel colour value is greater than 0 draw black, or else white."

**Pull request merged**
