### PR TITLE
Created CPU class

### PR DESCRIPTION
**Pull request by Quaker762**
Start to a CPU class. Register definition structs set up.

### CODE REVIEW

**Comment by wornwinter** [comment]
Forgot to say. You have write access. You don't need to fork lol.

**Comment by Quaker762** [comment]
Ah okay. How do we stop merge conflicts then? If I commit something and you're working on something, it breaks.

**Comment by wornwinter** [comment]
We just agree to work on separate parts. Or, for example, say you're working on the cpu, and I'm working on the debugger, but you make a commit from the last time I pulled to my local repo, I just rebase it by pulling again, then commit with my changes.

**Comment by Quaker762** [comment]
Okay, got it.

**Comment by wornwinter** [comment]
Great :)

So in the meantime, do you want to work on the CPU, and I'll work on the Gameboy class + MMU?

**Comment by Quaker762** [comment]
Yeah sure, sounds good.

**Pull request merged**
