### PR TITLE
Created Opcode table

### PR DESCRIPTION
**Pull request by Quaker762**
Created an opcode table and generic (NOP) opcode function stub.

I'm going to use pull requests as I don't trust myself with handling the master branch. I'll probably end up fucking something up, as GIT seems to REALLY hate me, not to mention the Windows version is a crock of shit lmao.

### CODE REVIEW

**Comment by wornwinter** [comment]
Looks good, but I think the opcode functions need to have meaningful names. What do you think?

**Comment by wornwinter** [comment]
Actually wait. That'd be a lot of legwork. As long as we comment in the header file beside each one stating what it does as we implement them.

**Comment by wornwinter** [comment]
Will merge when I'm not on mobile

**Comment by Quaker762** [comment]
Yeah I was considering doing meaningful names, but it did seem like a little bit of extra work. If you'd like, I can rename the functions so they o make more sense, however we can make a disassembled that disassembles a rim and prints out the current instruction.

**Comment by wornwinter** [comment]
Yeah we can do that. It's a lot of pointless work now that I think about it.

On another note, I'm going to flesh out the MMU etc tomorrow at some point. Been pretty busy lately lol.

But the commits look good. Already merged :)

**Pull request merged**
